

title: XDAG | A new DAG-based cryptocurrency
description:  A new DAG-based cryptocurrency
baseurl: ""
url: ""

paginate: 6
paginate_path: '/:num'

plugins:
  - jekyll-paginate

exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock', 'package.json', 'package-lock.json', 'vendor']


